### ISSUE TITLE
Error: Guest Wifi - Could not get Guest Wifi state

### ISSUE THREAD

**Issue by springstan** [mammuth/ha-fritzbox-tools#36] opened 2019-11-10 19:13 UTC
Great custom component, I really love what you guys are doing!

Unfortunately, I have this error message in my logs, which shows up a lot of times, since the last release:
```
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/fritzbox_tools/switch.py", line 327, in _async_fetch_update
    status = self.fritzbox_tools.connection.call_action('WLANConfiguration:3', 'GetInfo')['NewStatus']
KeyError: 'NewStatus'
```
Therefore, I cannot use the `switch.fritzbox_guest_wifi` since it is constantly `unavailable`.

Configuration.yaml:
```yaml
fritzbox_tools:
  host: !secret fritzbox_host
  username: !secret fritzbox_username
  password: !secret fritzbox_password
```

Hope you guys can help me out :)

**Comment by mammuth** [comment] 2019-11-10 19:36
Thanks for reporting. 👍 

Do you have some experience with python? 
Then you could try the following:
install fritzconnections via `pip install -U fritzconnection`
Then do the following in a python REPL:
```python
import fritzconnection as fc
c = fc.FritzConnection(
    address='yourhost',
    port= 49000,
    user='yourusername',
    password='yourpassword'
)
print(c.call_action('WLANConfiguration:3', 'GetInfo'))
```

Besides, might it be possible that we're running into a race condition, where `self.fritzbox_tools.connection` isn't fully initialised yet (/authenticated with the router), when the switch is being setup? (just a braindump for later reference, no real question)

**Comment by springstan** [comment] 2019-11-10 19:50
Sure thing 👍 

Yeah I have some experience with python so I hope that I can help you get to the bottom of this.
After doing that I get the following error:
```
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\fritzconnection\fritzconnection.py", line 376, in _get_action
    service = self.services[service_name]
KeyError: 'WLANConfiguration:3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python37\lib\site-packages\fritzconnection\fritzconnection.py", line 405, in call_action
    action = self._get_action(service_name, action_name)
  File "C:\Program Files\Python37\lib\site-packages\fritzconnection\fritzconnection.py", line 378, in _get_action
    raise ServiceError('Unknown Service: ' + service_name)
fritzconnection.fritzconnection.ServiceError: Unknown Service: WLANConfiguration:3
```

**Comment by AaronDavidSchneider** [comment] 2019-11-11 07:40
Looks like fritzconnection has a problem to call services on the fritzbox.
Could you please have a look in your fritzbox settings and check both marks of `Access Settings in the Home Network` in
`Home Network`- `Network`- `Network Settings`  are ticked?

Is the connectivity sensor created by home assistant?

**Comment by springstan** [comment] 2019-11-11 15:59
Of course, both checkboxes are ticked under `Access Settings in the Home Network`.
Yes, the connectivity sensor is successfully created by Home Assistant.
To investigate `Access Settings in the Home Network` I used the same credentials and had no problems logging in.

**Comment by AaronDavidSchneider** [comment] 2019-11-11 16:43
That doesn't look good... You should perhaps consider to open an issue at https://github.com/kbr/fritzconnection.

Can you recall since when you encounter this issue? 
Homeassistant uses fritzconnection version 0.8.4 since version 0.101.

Could you also try
```
c.call_action(
                'Layer3Forwarding:1',
                'GetDefaultConnectionService'
                )['NewDefaultConnectionService']
```

what fritzbox are you using?

**Comment by springstan** [comment] 2019-11-11 17:01
Sure I can open an issue there. Could you explain to me what exactly is not working?
So that I can fill out a detailed and easy to understand issue 😊
I think this occurred after upgradring Home Assistant to 0.101. 
Do any breaking changes from fritzconnection exist that could relate to this?
This code snippet gives me the following: `1.WANPPPConnection.1`
I am currently using the [FritzBox 7560](https://avm.de/produkte/fritzbox/fritzbox-7560/).

**Comment by AaronDavidSchneider** [comment] 2019-11-11 19:10
This is my diagnosis:
```py
print(c.call_action('WLANConfiguration:3', 'GetInfo'))
```
should not return an empty dict (`{}`), but rather a dict with many keys, like:
```py
{'NewEnable': '0', 'NewStatus': 'Disabled', 'NewMaxBitRate': 'Auto', 'NewChannel': 1, 'NewSSID': '...', 'NewBeaconType': '11i', 'NewMACAddressControlEnabled': '0', 'NewStandard': 'n', 'NewBSSID': '...', 'NewBasicEncryptionModes': 'None', 'NewBasicAuthenticationMode': 'None', 'NewMaxCharsSSID': 32, 'NewMinCharsSSID': 1, 'NewAllowedCharsSSID': '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz !"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~', 'NewMinCharsPSK': 64, 'NewMaxCharsPSK': 64, 'NewAllowedCharsPSK': '0123456789ABCDEFabcdef'}
```
These informations are however needed by homeassistant to determine the status of your guestwifi switch (`NewStatus`). Homeassistant can't create the guest wifi switch without this knowledge.

As you showed me with `1.WANPPPConnection.1` fritzconnection seems to authenticate well with your fritzbox and is also able request informations  from it.

You should also double check that it works with the earlier fritzconnection version 0.6.5:
```
pip uninstall fritzconnection
pip install fritzconnection==0.6.5
```
Then mention that this error occured when updating to version 0.8.4.
Also mention your fritzbox and that you ticked the settings in `Access Settings in the Home Network`.

**Comment by springstan** [comment] 2019-11-11 19:22
@AaronDavidSchneider okay thanks for your information and your diagnosis of the problem.
I will open an issue at https://github.com/kbr/fritzconnection after testing checking that it works with the earlier version (0.6.5).

**Comment by dennis84de** [comment] 2019-11-14 20:37
I've had the same problem some time ago when I worked on a cumstom component for myself.

I found out that for some fritzboxes you need the following code (see the "2"):
> print(c.call_action('WLANConfiguration:2', 'GetInfo'))

This depends on the wifi configuration (2.4ghz or 5ghz). When the fritzbox supports only 2.4ghz you need the code above.

I think it would be the best when you could set the interface in the configuration.

**Comment by mammuth** [comment] 2019-11-14 20:47
Great info, thanks @dennis84de!

**Comment by AaronDavidSchneider** [comment] 2019-11-15 05:32
> This depends on the wifi configuration (2.4ghz or 5ghz). When the fritzbox supports only 2.4ghz you need the code above.

@springstan uses a Fritzbox 7560 with 2.4Ghz and 5Ghz. I am not quite sure if that’s the real issue. Can you test this @springstan?

@mammuth: if this is really the case, we should implement WLANConfiguration:2 as an automatic fallback (testing with 3, if empty dict: use 2)
What do you think?

**Comment by springstan** [comment] 2019-11-15 08:02
@AaronDavidSchneider sure I will test this as soon as possible and get back to you.

@dennis84de thanks for the insight! Pretty sure this can solve my problem.

**Comment by springstan** [comment] 2019-11-15 16:01
@AaronDavidSchneider so I tested the following:
```python
print(c.call_action('WLANConfiguration:2', 'GetInfo'))
```
And I get back a filled dictionary that matches your description. 
However, the value for the key `NewSSID` is not the SSID of my guest wifi. 
Instead it is just the SSID of my normal wifi network.

That is not the expected behaviour, is it?

**Comment by AaronDavidSchneider** [comment] 2019-11-15 17:01
> That is not the expected behaviour, is it?
It is the expected behaviour: You have dual band (2,4GHz and 5GHz), therefore `WLANConfiguration:2` and `WLANConfiguration:1` are  your default networks. Meanwhile `WLANConfiguration:3` should be the guestwifi. 
@springstan: Are you able to switch the guestwifi in your fritzbox settings?

**Comment by springstan** [comment] 2019-11-15 17:11
> @springstan: Are you able to switch the guestwifi in your fritzbox settings?

Do you mean if I can turn the guest wifi on and off? Yes I can do that in the fritzbox settings.

**Comment by AaronDavidSchneider** [comment] 2019-11-16 13:11
> > @springstan: Are you able to switch the guestwifi in your fritzbox settings?
> 
> Do you mean if I can turn the guest wifi on and off? Yes I can do that in the fritzbox settings.
> 
> Just tested it and yes you are right `WLANConfiguration:1` and `WLANConfiguration:2` give back a dictionary with the details about my default wifi and `WLANConfiguration:1` returns `{}`.

Maybe we get more insight with the information from http://<ip-of-fritzbox>:49000/tr64desc.xml.
@springstan could you check for the snippet in the response that looks like this:
```XML
urn:dslforum-org:service:WLANConfiguration:3urn:WLANConfiguration-com:serviceId:WLANConfiguration3/upnp/control/wlanconfig3/upnp/control/wlanconfig3/wlanconfigSCPD.xml
```
Or do you only have the same services for `WLANConfiguration:2` and `WLANConfiguration:1`

**Comment by springstan** [comment] 2019-11-16 19:32
> Maybe we get more insight with the information from http://ip-of-fritzbox:49000/tr64desc.xml.
@springstan could you check for the snippet in the response that looks like this:

My snippet looks like the one you posted:
```xml
<service>
  <serviceType>urn:dslforum-org:service:WLANConfiguration:3</serviceType>
  <serviceId>urn:WLANConfiguration-com:serviceId:WLANConfiguration3</serviceId>
  <controlURL>/upnp/control/wlanconfig3</controlURL>
  <eventSubURL>/upnp/control/wlanconfig3</eventSubURL>
  <SCPDURL>/wlanconfigSCPD.xml</SCPDURL>
</service>
```
And I have these services for all three of them, so `WLANConfiguration:1`, `WLANConfiguration:2` and `WLANConfiguration:3`.

**Comment by AaronDavidSchneider** [comment] 2019-11-16 20:08
Alright. Thankyou for your response @springstan. 
Can you try to enable the guest wlan with
`c.call_action('WLANConfiguration:3', 'SetEnable', NewEnable=1)` 
and disable it with 
`c.call_action('WLANConfiguration:3', 'SetEnable', NewEnable=0)`.
Do these commands work? Check if your guestwifi gets turned on or off
As you have demonstrated with the above your fritzbox correctly broadcasts the service to switch the guestwifi state and get its information. 

Did you try to restart your fritzbox? Or maybe to reset it?

I think there is not much that can be tested anymore....

**Comment by springstan** [comment] 2019-11-16 20:21
No problem @AaronDavidSchneider 
> ```
> c.call_action('WLANConfiguration:3', 'SetEnable', NewEnable=1)
> c.call_action('WLANConfiguration:3', 'SetEnable', NewEnable=0)
> ```

Yes those commands work. They take a second or two to apply, but they definitely work!
No I have not tried to restart or reset my fritzbox. However, I can try that tomorrow and check if anything has changed.

**Comment by springstan** [comment] 2019-11-18 16:59
@AaronDavidSchneider a simple restart solved this issue 🙈

**Comment by mammuth** [comment] 2019-11-18 17:16
Interesting. Whatever the reason was, it's apparently out of control of our component. So I guess it's ok to close this issue.

**Closed by mammuth** 2019-11-18 17:16 UTC
Labels: type:bug, upstream-issue
