### ISSUE TITLE
Missing logo brand for hass 0.108 (now beta)

### ISSUE THREAD

**Issue by sagitt** [mammuth/ha-fritzbox-tools#78] opened 2020-04-03 19:10 UTC
Missing brands for this integration.

https://rc.home-assistant.io/blog/2020/03/27/release-108/

Integration logos & icons
We have created a new repository on GitHub containing all the brand icons and logos Home Assistant is able to integrate with. These images are, for example, used in our documentation.

In 0.108, we made a start on using the content from this repository in the Home Assistant frontend. The device information page got a layout update and the integrations page as well.

These pages will now show the icons and logos matching the integration.

**Comment by mammuth** [comment] 2020-05-16 15:43
Closing as duplicate of #94

**Closed by mammuth** 2020-05-16 15:43 UTC
