### ISSUE TITLE
Two Errors since v1.13x ...

### ISSUE THREAD

**Issue by bussio** [mammuth/ha-fritzbox-tools#124] opened 2020-10-27 12:01 UTC
Since version 1.13x I have 2 error messages in the logfile:

Logger: homeassistant
Source: custom_components/fritzbox_tools/switch.py:33 
First occurred: 12:49:00 (2 occurrences) 
Last logged: 12:49:00

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/fritzconnection/core/fritzconnection.py", line 204, in call_action
    service = self.device_manager.services[service_name]
KeyError: 'X_AVM-DE_OnTel1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/fritzbox_tools/switch.py", line 33, in _create_deflection_switches
    deflections_response = fritzbox_tools.connection.call_action("X_AVM-DE_OnTel:1", "GetNumberOfDeflections")
  File "/usr/local/lib/python3.8/site-packages/fritzconnection/core/fritzconnection.py", line 206, in call_action
    raise FritzServiceError(f'unknown service: "{service_name}"')
fritzconnection.core.exceptions.FritzServiceError: unknown service: "X_AVM-DE_OnTel1"

_and here is the second one:_

__
Logger: custom_components.fritzbox_tools.binary_sensor
Source: custom_components/fritzbox_tools/binary_sensor.py:69 
Integration: FRITZ!Box Tools (documentation) 
First occurred: 12:48:37 (16 occurrences) 
Last logged: 12:55:38

Error getting the state from the FRITZ!Box
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/fritzconnection/core/fritzconnection.py", line 204, in call_action
    service = self.device_manager.services[service_name]
KeyError: 'WANCommonInterfaceConfig1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/fritzbox_tools/binary_sensor.py", line 70, in _async_fetch_update
    is_up = await self.hass.async_add_executor_job(connection)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/fritzbox_tools/binary_sensor.py", line 69, in <lambda>
    connection = lambda: self.fritzbox_tools.connection.call_action("WANCommonInterfaceConfig1", "GetCommonLinkProperties")["NewPhysicalLinkStatus"]
  File "/usr/local/lib/python3.8/site-packages/fritzconnection/core/fritzconnection.py", line 206, in call_action
    raise FritzServiceError(f'unknown service: "{service_name}"')
fritzconnection.core.exceptions.FritzServiceError: unknown service: "WANCommonInterfaceConfig1"

**Comment by AaronDavidSchneider** [comment] 2020-10-27 12:10
Thanks for reporting. Both errors are not related to the latest release but rather to your specific fritzbox.
Can you tell us, which FB you are using (and which version of FRITZ!OS)?

**Comment by bussio** [comment] 2020-10-27 12:15
I use a FB 6591 with FritzOS 07.21. It is a cable box at the provider Vodafone.

**Comment by AaronDavidSchneider** [comment] 2020-10-27 12:26
> I use a FB 6591 with FritzOS 07.21. It is a cable box at the provider Vodafone.

ok. This FB should have no problems with the mentioned services. Did you already perform the usual debugging? (try to restart the FB, readd component in ha, restart HA, carefully reading the readme, etc...)

**Comment by bussio** [comment] 2020-10-27 14:20
I have done it all again... unfortunately nothing changes. The error messages remain the same.

**Comment by AaronDavidSchneider** [comment] 2020-10-27 16:25
Are you certain that you did not have this error in v1.12?

**Comment by bussio** [comment] 2020-10-27 17:30
With v1.12 I have a different error message:

Logger: custom_components.fritzbox_tools.switch
Source: custom_components/fritzbox_tools/switch.py:77 
Integration: FRITZ!Box Tools (documentation) 
First occurred: 18:22:28 (1 occurrences) 
Last logged: 18:22:28

Port switches could not be enabled. Check if your fritzbox is able to do port forwardings!
Traceback (most recent call last):
  File "/config/custom_components/fritzbox_tools/switch.py", line 77, in _create_port_switches
    portmap = fritzbox_tools.connection.call_action(
  File "/usr/local/lib/python3.8/site-packages/fritzconnection/core/fritzconnection.py", line 207, in call_action
    return self.soaper.execute(service, action_name, arguments)
  File "/usr/local/lib/python3.8/site-packages/fritzconnection/core/soaper.py", line 170, in execute
    return handle_response(response)
  File "/usr/local/lib/python3.8/site-packages/fritzconnection/core/soaper.py", line 154, in handle_response
    return self.parse_response(response, service, action_name)
  File "/usr/local/lib/python3.8/site-packages/fritzconnection/core/soaper.py", line 197, in parse_response
    value = self.conversion_table[data_type](value)
ValueError: invalid literal for int() with base 10: '55536-55566'

But what I do not understand, because my settings are as follows:

![2020-10-27_18-26-08](https://user-images.githubusercontent.com/48105172/97338706-fbd7be00-1881-11eb-8fec-36b07cac2b21.jpg)

The previous two error messages do not appear ...

**Comment by AaronDavidSchneider** [comment] 2020-10-27 17:45
Ok This error is the same as #75.
I will have a look into it tomorrow 🕵

**Comment by AaronDavidSchneider** [comment] 2020-10-28 10:38
So the 1.12 error is related to #75 meaning that you can not use port ranges for the port forwarding switch.

But I don't know why on earth you get the first two errors in 1.13, since they have nothing to do with the upgrade from 1.12 to 1.13.

There are a few things that we can try now:

1. Share a bit about your environment: which other fritzboxes do you have in your network? How did you setup fritzbox_tools (YAML, discovery, manual ui)?
2. please try if you get the same errors in 1.12 if you disable the portforwarding switches (during configuration)
3. if you know a bit python we could test where the problem is by debugging with fritzconnection

Cheers
Aaron

**Comment by bussio** [comment] 2020-10-28 12:57
In addition to the FB 6591, I operate the FRITZ! repeaters 2400 and 3000. I also operate a FRITZ! DECT Repeater 100 and some FRITZ! DECT 200. 

Entries Yaml:

    - type: entities
      style: |
        ha-card {
          --ha-card-background: rgba(255, 255, 255, 0.3);
          border-radius: 15px;  
        }
      title: Fritz!Box Tools
      show_header_toggle: false
      entities: 
        - binary_sensor.fritzbox_6591_cable_connectivity
        - switch.fritzbox_6591_cable_guest_wifi
        - switch.fritzbox_6591_cable_deflection_0
        - switch.fritzbox_6591_cable_wifi
        - switch.fritzbox_6591_cable_wifi_5ghz

    - type: entities
      style: |
        ha-card {
          --ha-card-background: rgba(255, 255, 255, 0.3);
          border-radius: 15px;  
        }
      title: Reconnect / Reboot FRITZ!Box
      show_header_toggle: false
      entities:
        - script.fritz_box_reconnect                                          
        - script.fritz_box_reboot
        - entity: sensor.public_ip_address                                      
          icon: mdi:ip-network

Unfortunately I can not serve with Python knowledge.

>>> please try if you get the same errors in 1.12 if you disable the portforwarding switches (during configuration)

![2020-10-28_13-47-45](https://user-images.githubusercontent.com/48105172/97438672-67bf3280-1925-11eb-96ae-9c8a75393d1a.jpg)

That's what I did ... the error will no longer appear in the log.

Bye 
Wolfgang

**Comment by AaronDavidSchneider** [comment] 2020-10-28 13:22
Hi,

thanks for testing! No errors in 1.13 with port forwarding switches disabled?

Cheers
Aaron

**Comment by bussio** [comment] 2020-10-28 13:43
I have installed the 1.13.o There is no error. In the integrations the two repeaters 2400/3000 appear now and want to be configured.

![2020-10-28_14-39-41](https://user-images.githubusercontent.com/48105172/97443915-db643e00-192b-11eb-8975-66cbcc3bcb8d.jpg)

Soll ich es wagen und die einrichten ;-)

**Comment by AaronDavidSchneider** [comment] 2020-10-28 13:50
> I have installed the 1.13.o There is no error. In the integrations the two repeaters 2400/3000 appear now and want to be configured.
> 
> ![2020-10-28_14-39-41](https://user-images.githubusercontent.com/48105172/97443915-db643e00-192b-11eb-8975-66cbcc3bcb8d.jpg)
> 
> Soll ich es wagen und die einrichten ;-)

Yes do it! I will close this issue as a duplicate of #75, if that is ok for you :D

**Comment by bussio** [comment] 2020-10-28 14:00
No sooner have I set up the two repeaters under the integrations than the above mentioned error messages are back.

**Comment by AaronDavidSchneider** [comment] 2020-10-28 15:02
Ah... looks like the errors are caused by the repeater!

And it makes sense: one of the error messages comes from the the phone deflection switch (which makes no sense for the repeater)

The second error: looks like the repeater is not supported by the binary sensor. I will try to come up with a fix.

**Comment by AaronDavidSchneider** [comment] 2020-10-28 15:36
Could you please try the current PR?

Just replace your files with the files from here: https://github.com/AaronDavidSchneider/ha-fritzbox-tools/tree/better_error

You should be able to add the repeaters with the new PR.

Thanks!

**Comment by bussio** [comment] 2020-10-28 15:57
I have exchanged the files and restarted. Now I got the following error message:

Logger: custom_components.fritzbox_tools.binary_sensor
Source: custom_components/fritzbox_tools/binary_sensor.py:74
Integration: FRITZ!Box Tools (documentation)
First occurred: 16:52:18 (2 occurrences)
Last logged: 16:52:18

Error getting the state from the FRITZ!Box
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/fritzconnection/core/fritzconnection.py", line 204, in call_action
    service = self.device_manager.services[service_name]
KeyError: 'WANIPConn1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/fritzbox_tools/binary_sensor.py", line 74, in _async_fetch_update
    self._is_on = self.hass.async_add_executor_job(self.fritzbox_tools.fritzstatus.is_connected)
  File "/usr/local/lib/python3.8/site-packages/fritzconnection/lib/fritzstatus.py", line 50, in is_connected
    status = self.fc.call_action('WANIPConn', 'GetStatusInfo')
  File "/usr/local/lib/python3.8/site-packages/fritzconnection/core/fritzconnection.py", line 206, in call_action
    raise FritzServiceError(f'unknown service: "{service_name}"')
fritzconnection.core.exceptions.FritzServiceError: unknown service: "WANIPConn1"

**Comment by AaronDavidSchneider** [comment] 2020-10-28 16:08
Ok. Looks like fritzconnection really doesn't like repeater... Since I don't have a repeater, we will have to do some weird debugging to get this working.

Please try again the updated files and report the error. We can hopefully find a solution with the new error.

**Comment by bussio** [comment] 2020-10-28 16:19
Here the result with the new files.
The first error message:

Logger: custom_components.fritzbox_tools.binary_sensor
Source: custom_components/fritzbox_tools/binary_sensor.py:74
Integration: FRITZ!Box Tools (documentation)
First occurred: 17:12:56 (2 occurrences)
Last logged: 17:12:56

dict_keys(['DeviceInfo1', 'DeviceConfig1', 'UserInterface1', 'WLANConfiguration1', 'WLANConfiguration2', 'WLANConfiguration3', 'Hosts1'])
dict_keys(['DeviceInfo1', 'DeviceConfig1', 'UserInterface1', 'WLANConfiguration1', 'WLANConfiguration2', 'WLANConfiguration3', 'WLANConfiguration4', 'Hosts1'])

and here is the second one... but you already know it:

Logger: custom_components.fritzbox_tools.binary_sensor
Source: custom_components/fritzbox_tools/binary_sensor.py:75
Integration: FRITZ!Box Tools (documentation)
First occurred: 17:12:56 (2 occurrences)
Last logged: 17:12:56

Error getting the state from the FRITZ!Box
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/fritzconnection/core/fritzconnection.py", line 204, in call_action
    service = self.device_manager.services[service_name]
KeyError: 'WANIPConn1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/fritzbox_tools/binary_sensor.py", line 75, in _async_fetch_update
    self._is_on = self.hass.async_add_executor_job(self.fritzbox_tools.fritzstatus.is_connected)
  File "/usr/local/lib/python3.8/site-packages/fritzconnection/lib/fritzstatus.py", line 50, in is_connected
    status = self.fc.call_action('WANIPConn', 'GetStatusInfo')
  File "/usr/local/lib/python3.8/site-packages/fritzconnection/core/fritzconnection.py", line 206, in call_action
    raise FritzServiceError(f'unknown service: "{service_name}"')
fritzconnection.core.exceptions.FritzServiceError: unknown service: "WANIPConn1"

**Comment by AaronDavidSchneider** [comment] 2020-10-28 16:27
Thanks!
There is no way to determine wether the repeater is connected or not. Therefore, we need to disable the connectivity sensor for repeaters...

Thanks again for testing. I also did not know that there can be 4 wifi networks for the 3000? How does it work? We might need to find a solution to this as well...

**Comment by AaronDavidSchneider** [comment] 2020-10-28 16:36
I have updated the files again. I tried to additionally incoorporate the 4 wifi networks.
I still do not know what the 4 wifi networks are. So, if you could toggle the four exposed switches for the repeater 3000, please let me know what they do :D

**Comment by bussio** [comment] 2020-10-28 16:40
The 3000 has 3 channels: 2.4GHZ and 2x 5GHz. 
"The FRITZ! repeater 3000 has three WLAN radio units: Two are intended for communication with WLAN devices in the 2.4GHz band and in the 5GHz band. The third radio unit enables optimal communication with the WLAN router. This radio unit uses the 5 GHz band."

**Comment by AaronDavidSchneider** [comment] 2020-10-28 16:42
Ah ok. Thanks! Can you please tell me which switch maps to which radio unit?

**Comment by bussio** [comment] 2020-10-28 16:58
Sorry, I (or the translator) did not understand this correctly. What do you mean exactly?

The good news ... there is no error message anymore!

**Comment by AaronDavidSchneider** [comment] 2020-10-28 17:03
Sorry :D 
In german: Ich wollte dich fragen, welcher Switch welches wifi netzwerk an und ausschaltet.

**Comment by bussio** [comment] 2020-10-28 18:23
Mmm, sorry, just had a power outage here ... so I'm just now getting back to you. 
Unfortunately I cannot answer the question you asked me. But as I understand it, the one 
the 2.4Ghz connection and the other one the 5Ghz connection. The 5Ghz connection that the repeater uses as a return line to the FB should not be available at all.

**Comment by AaronDavidSchneider** [comment] 2020-10-28 19:12
The following services are exposed by the repeater:

dict_keys(['DeviceInfo1', 'DeviceConfig1', 'UserInterface1', 'WLANConfiguration1', 'WLANConfiguration2', 'WLANConfiguration3', 'WLANConfiguration4', 'Hosts1'])

Meaning you can control four networks. One is 2.4ghz, one is the guest WiFi, one is the standard 5ghz and one is the connection with the main router.

I am just not sure which is which. But all of them are exposed by the Fritzbox and are controlled by Fritzbox tools.

A standard Fritzbox has the following mapping:

1: 2.4ghz, 2: 5, 3: guest WiFi.

That is why we chose the naming the way we did, but this doesn't work with your repeater, because it exposes 4 networks :D

**Comment by AaronDavidSchneider** [comment] 2020-10-28 19:14
To test: 
Just toggle the exposed switches and let us know what you can see/ what happens in the Fritzbox web interface.

**Comment by bussio** [comment] 2020-10-28 19:29
Correct, I forgot the guest wlan. 
If I switch the switch "switch.fritzbox_6591_cable_guest_wifi", then the guest access is switched on or off in the FB web interface.
With the switch "switch.fritzbox_6591_cable_wifi" the 2,4Ghz networks are switched and with the switch "switch.fritzbox_6591_cable_wifi_5ghz" I switch the 5Ghz networks.

**Comment by AaronDavidSchneider** [comment] 2020-10-28 20:28
Ok but I am more curious about the switches for the repeater.

they should have the name:
switch.fritzbox_fritzrepeater3000_wifi ...
Or something like this.

**Comment by bussio** [comment] 2020-10-29 11:58
So, today I tried the whole thing with the switches of the Repeater 2400. With me the repeaters run in mesh mode. So the guest access from the repeater cannot be triggered. It is only switched by the Mesh-Master 6591.
The switching of the 2.4- and 5Ghz network works for the range of devices attached to the router.

**Comment by AaronDavidSchneider** [comment] 2020-10-29 18:28
ok thanks for testing. Do you see any nescessity to change something? Or are the repeaters working as intended?

**Comment by bussio** [comment] 2020-10-29 18:32
From my side, the change works fine.

**Comment by mammuth** [comment] 2020-10-31 22:16
The fix is part of `1.13.2`.

**Closed by mammuth** 2020-10-31 22:16 UTC
Labels: type:bug
