### ISSUE TITLE
[FR] Consider merging with official integration

### ISSUE THREAD

**Issue by chemelli74** [mammuth/ha-fritzbox-tools#120] opened 2020-10-10 17:17 UTC
Hi,

I noticed that official HA integration, "fritz", doesn't have a maintainer.
Would be nice to merge that and this.

What you think ?

Simone

**Comment by mammuth** [comment] 2020-10-12 20:30
That has been the idea from the beginning. 

Closing as duplicate of https://github.com/mammuth/ha-fritzbox-tools/issues/29

**Closed by mammuth** 2020-10-12 20:30 UTC
