### ISSUE TITLE
Error after update to HA 2021.7: cannot import name 'get_all_profiles' from 'fritzprofiles'

### ISSUE THREAD

**Issue by DarkWarden85** [mammuth/ha-fritzbox-tools#171] opened 2021-07-07 17:45 UTC
Hi all,

After today's update to Home Assistant 2021.7, the fritz-box-tools is unable to complete it's setup with the follwing error message from the logs:

> 2021-07-07 19:21:35 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration fritz: cannot import name 'get_all_profiles' from 'fritzprofiles' (/usr/local/lib/python3.9/site-packages/fritzprofiles/__init__.py)
2021-07-07 19:21:35 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 696, in async_create_flow
integration.get_platform("config_flow")
File "/usr/src/homeassistant/homeassistant/loader.py", line 498, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 503, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 855, in exec_module
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "/usr/src/homeassistant/homeassistant/components/fritz/__init__.py", line 17, in <module>
from .common import FritzBoxTools, FritzData
File "/usr/src/homeassistant/homeassistant/components/fritz/common.py", line 18, in <module>
from fritzprofiles import FritzProfileSwitch, get_all_profiles
ImportError: cannot import name 'get_all_profiles' from 'fritzprofiles' (/usr/local/lib/python3.9/site-packages/fritzprofiles/__init__.py)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 153, in async_init
flow, result = await task
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 171, in _async_init
flow = await self.async_create_flow(handler, context=context, data=data)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 703, in async_create_flow
raise data_entry_flow.UnknownHandler
homeassistant.data_entry_flow.UnknownHandler

I am running Home Assistant OS on a Raspberry Pi 4 4GB.
I installed Fritz Box Tools via HACS. I tried uninstalling the integration and reinstall it again, however the uninstallation fails with the following error message:

> 2021-07-07 19:43:16 ERROR (MainThread) [homeassistant.setup] Setup failed for fritz: Unable to import component: cannot import name 'get_all_profiles' from 'fritzprofiles' (/usr/local/lib/python3.9/site-packages/fritzprofiles/__init__.py)
2021-07-07 19:43:23 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 70, in delete
result = await hass.config_entries.async_remove(entry_id)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 809, in async_remove
await entry.async_remove(self.hass)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 467, in async_remove
component = integration.get_component()
File "/usr/src/homeassistant/homeassistant/loader.py", line 490, in get_component
cache[self.domain] = importlib.import_module(self.pkg_path)
File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 855, in exec_module
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "/usr/src/homeassistant/homeassistant/components/fritz/__init__.py", line 17, in <module>
from .common import FritzBoxTools, FritzData
File "/usr/src/homeassistant/homeassistant/components/fritz/common.py", line 18, in <module>
from fritzprofiles import FritzProfileSwitch, get_all_profiles
ImportError: cannot import name 'get_all_profiles' from 'fritzprofiles' (/usr/local/lib/python3.9/site-packages/fritzprofiles/__init__.py)

Is there any way to fix this?

**Comment by AaronDavidSchneider** [comment] 2021-07-08 04:59
This is likely caused by the core integration Fritz.

This custom component is now fully succeeded by the Fritz core integration

**Comment by Friedrieck** [comment] 2021-07-08 08:31
Indeed, this custom component is now incompatible with the core integration. It must be removed completely for the core integration to load correctly, see https://github.com/home-assistant/core/issues/52632
Thanks again to all contributors!

**Comment by groenmarsmannetje** [comment] 2021-07-08 08:42
Just a suggestion. The read me document of this custom component contains useful examples that are not in [the core integration documentation](https://www.home-assistant.io/integrations/fritz/). Would be a pity if that information is lost.

**Comment by AaronDavidSchneider** [comment] 2021-07-08 08:44
> Just a suggestion. The read me document of this custom component contains useful examples that are not in [the core integration documentation](https://www.home-assistant.io/integrations/fritz/). Would be a pity if that information is lost.

Thats true! Feel free to open up a PR in https://github.com/home-assistant/home-assistant.io

**Comment by DarkWarden85** [comment] 2021-07-08 10:09
Thanks for all your suggestions. With the instructions in home-assistant/core#52632 I was able to successfully uninstall the custom component and get the official fritz integration working again.

**Comment by chemelli74** [comment] 2021-07-08 15:27
@DarkWarden85, you can then close this issue here ;-)

Simone

**Closed** 2021-07-08 15:28 UTC
