### ISSUE TITLE
Errors in 0.117

### ISSUE THREAD

**Issue by robyevolution** [mammuth/ha-fritzbox-tools#126] opened 2020-10-29 22:02 UTC
hello when i upgraded home assistant to 0.117 there are errors loop in the log:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/fritzbox_tools/binary_sensor.py", line 70, in _async_fetch_update
    is_up = await self.hass.async_add_executor_job(connection)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/fritzbox_tools/binary_sensor.py", line 69, in <lambda>
    connection = lambda: self.fritzbox_tools.connection.call_action("WANCommonInterfaceConfig1", "GetCommonLinkProperties")["NewPhysicalLinkStatus"]
  File "/srv/homeassistant/lib/python3.8/site-packages/fritzconnection/core/fritzconnection.py", line 206, in call_action
    raise FritzServiceError(f'unknown service: "{service_name}"')
fritzconnection.core.exceptions.FritzServiceError: unknown service: "WANCommonInterfaceConfig1"
2020-10-29 23:00:49 ERROR (MainThread) [custom_components.fritzbox_tools.binary_sensor] Error getting the state from the FRITZ!Box
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/fritzconnection/core/fritzconnection.py", line 204, in call_action
    service = self.device_manager.services[service_name]
KeyError: 'WANCommonInterfaceConfig1'

**Comment by AaronDavidSchneider** [comment] 2020-10-29 22:05
Hi, thanks for reporting!
Do you use a repeater?
Please check #124

**Comment by robyevolution** [comment] 2020-10-29 22:51
i read that post but i didn't understand how to fix

**Comment by AaronDavidSchneider** [comment] 2020-10-30 08:36
If your problem is caused by a repeater that you tried to setup in HA you can try the following:

Just replace your files in config/custom_components with the files from here: https://github.com/AaronDavidSchneider/ha-fritzbox-tools/tree/better_error

Let me know if you need any more help.

Thanks!

**Comment by robyevolution** [comment] 2020-10-30 09:20
with the fix  there are this error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/fritzbox_tools/switch.py", line 69, in _create_port_switches
    connection_type = fritzbox_tools.connection.call_action(
  File "/srv/homeassistant/lib/python3.8/site-packages/fritzconnection/core/fritzconnection.py", line 206, in call_action
    raise FritzServiceError(f'unknown service: "{service_name}"')
fritzconnection.core.exceptions.FritzServiceError: unknown service: "Layer3Forwarding1"
2020-10-30 10:17:47 ERROR (SyncWorker_11) [custom_components.fritzbox_tools.switch] Port switches could not be enabled. Check if your fritzbox is able to do port forwardings!
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/fritzconnection/core/fritzconnection.py", line 204, in call_action
    service = self.device_manager.services[service_name]
KeyError: 'Layer3Forwarding1'

**Comment by AaronDavidSchneider** [comment] 2020-10-30 09:22
You need to disable port forwarding switches for the repeater (there are no ports to be opened for the repeater...). I will upload a fix. Thanks!

**Comment by AaronDavidSchneider** [comment] 2020-10-30 09:31
You could try again with the updated files. It should now deal with the case where port forwarding switches are not possible.

**Comment by robyevolution** [comment] 2020-10-30 10:20
now works!

**Comment by AaronDavidSchneider** [comment] 2020-10-30 10:21
Thanks for testing. I will close this issue since it is a duplicate of #124.

**Closed by AaronDavidSchneider** 2020-10-30 10:21 UTC
