### ISSUE TITLE
Switch uptime to DEVICE_CLASS_TIMESTAMP

### ISSUE THREAD

**Issue by chemelli74** [mammuth/ha-fritzbox-tools#114] opened 2020-09-22 15:07 UTC
Hi,

can you please consider switching uptime to timestamp ?
All integrations are switching, as this will follow the core rules and will be a lot more performance that using seconds/ string.

Thx,

Simone

**Comment by AaronDavidSchneider** [comment] 2020-09-22 15:10
Hi,

can you please explain a bit further what you are talking about?

Thanks!

**Comment by chemelli74** [comment] 2020-09-22 15:19
I'm asking to move those properties:

![image](https://user-images.githubusercontent.com/57354320/93902226-9c711600-fcf7-11ea-8ba4-55035bace9bb.png)

to 1 in timestamp format.
This way you won't update the DB each and every second but only on restart.

Simone

**Comment by AaronDavidSchneider** [comment] 2020-09-22 15:26
Thanks for the explaination. Do you have an example component that uses this method? Or a link to the developer docs?

**Comment by chemelli74** [comment] 2020-09-22 15:38
> Thanks for the explaination. Do you have an example component that uses this method? Or a link to the developer docs?

Here you are: https://github.com/home-assistant/core/blob/040075427040cd60bceb2aa0c589730e3c79e251/homeassistant/components/brother/sensor.py#L83

Simone

**Comment by AaronDavidSchneider** [comment] 2020-09-22 16:34
Thanks for the link! 

This only makes sense if a different sensor is spawned for every attribute ("modelname", "external_ip", "external_ipv6","uptime","str_uptime"). 
For example: One sensor for uptime, one for status (connected or not), one for external_ip and one for external_ipv6. And additional sensors for the open PR  #64, #19

This would close #93.

What do you think @mammuth?

Could you implement it @chemelli74?

**Comment by mammuth** [comment] 2020-09-22 17:03
Yep, this issue is basically a duplicate of #93 which we just didn't implement so far. But we should probably really do so, since it's putting load onto the state machine and db.

**Comment by AaronDavidSchneider** [comment] 2020-10-05 05:44
Closed by latest release.

**Closed by AaronDavidSchneider** 2020-10-05 05:44 UTC
Labels: type:enhancement
