### ISSUE TITLE
FritzStatus() not using provided credentials to fetch the info

### ISSUE THREAD

**Issue by da-anda** [mammuth/ha-fritzbox-tools#92] opened 2020-05-04 13:16 UTC
Hi,

I have disabled the "public" upnp data in my FritzBox since I do not wish to have this service and it's data being announced publicly in my network. Everything works fine, even all FritzBox mobile apps and they can show all the data, since they all use the credentials provided to them. Fritzbox-tools also uses the credentials for most things, but as it seems those get entirely ignored for the `FritzStatus` python object. Is there any way you can fix this, or does this have to be fixed in the upstream python lib? It's at least annoying and for now I have to just uncomment the initialisation of this object. I still get an error in the log file that way, but at least the rest of the component keeps working (like the wifi switch).

**Comment by mammuth** [comment] 2020-05-04 19:21
Indeed sounds, like it might be an upstream issue with `fritzconnection`. You could try reproducing the issue outside of fritzbox-tools, by directly using fritzconnection and then open an issue at the upstream repository, if the issue still persists.

**Comment by chemelli74** [comment] 2021-07-08 15:31
This custom integration is now deprecated because is fully merged into HomeAssistant core.

I would suggest you configure the new integration and retest your issue.
After reading the [documentation](https://www.home-assistant.io/integrations/fritz), if still present then open a issue on HomeAssistant Core repository.

Simone

**Closed** 2021-07-08 15:31 UTC
Labels: type:bug, upstream-issue
