### ISSUE TITLE
Switch Problem

### ISSUE THREAD

**Issue by legolas0802** [mammuth/ha-fritzbox-tools#20] opened 2019-10-12 17:52 UTC
I installed the custom component, but it doesn't create the switches for me. in the hassio log I find the following error:

Error while setting up platform fritzbox_tools
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/fritzbox_tools/switch.py", line 23, in setup_platform
    port_forwards_count: int = fritzbox_tools.connection.call_action('WANIPConnection:1', 'GetPortMappingNumberOfEntries')["NewPortMappingNumberOfEntries"]
KeyError: 'NewPortMappingNumberOfEntries'

**Comment by mammuth** [comment] 2019-10-13 13:48
Thanks for reporting. 
Looks like the Fritzbox doesn't reply with the configured port forwardings and then the whole setup function times out. 

So, beside trying to understand why the request doesn't get a response (in time), it might be a good idea to add a timeout to this request?

**Comment by legolas0802** [comment] 2019-10-13 17:47
I removed the port forward part of the configuration and the switches appeared. how can I increase the timeout and see if I can use the custom component in all its functions?

**Comment by mammuth** [comment] 2019-10-13 17:54
The hit timeout is set by the home assistant core. 
We would need to implement an own timeout around those faulty requests (or even better understand why the Fritzbox is not responding).

**Comment by AaronDavidSchneider** [comment] 2019-10-13 18:18
@legolas0802 could you maybe provide information about your setup (hardware, wired/wifi, which Fritzbox, etc)

Can you reproduce the error after multiple reboots? Do you have „selbstständige Portfreigabe“ enabled for your home assistant device? Do you use your Fritzbox with DSLite (no ipv4 portforwarding possible)?

I agree with @mammuth. Looks like this is due to the connection with the Fritzbox.

**Comment by legolas0802** [comment] 2019-10-13 18:36
I removed the port forward part of the configuration and the switches appeared. how can I increase the timeout and see if I can use the custom component in all its functions? I use fritzbox 7490, hassio works with wired. Possible that the problem is that I'm using a USB stick to give the internet to the fritzbox?

**Comment by AaronDavidSchneider** [comment] 2019-10-13 19:12
@legolas0802: If you have a data stick you might have Dslite.
Please check: https://www.wieistmeineip.de/ipv6-test/

Please check if you are able to open ipv4 ports in your Fritzbox configuration. If this is not possible the port switch will fail to initialise.

Our port switches only work with ipv4 port forwardings.

**Comment by legolas0802** [comment] 2019-10-14 10:23
the problem is the usb stick, thank you!!!

**Comment by mammuth** [comment] 2019-10-14 10:35
Glad it's resolved for you!

I'll keep this issue open because the component should handle such cases.

**Comment by AaronDavidSchneider** [comment] 2019-10-14 11:09
@mammuth: we should check the ipv4 status before creating the switches

**Comment by AaronDavidSchneider** [comment] 2019-10-14 11:41
I added a try except statement in the setup of the platform.

**Comment by mammuth** [comment] 2019-10-16 08:49
@legolas0802 could you upgrade to 1.2.2 (should be available through HACS) and check whether the component is not crashing anymore?

**Comment by AaronDavidSchneider** [comment] 2019-10-16 09:09
@mammuth: I think you forgot to include the fix itself.

**Comment by mammuth** [comment] 2019-10-16 09:13
> @mammuth: I think you forgot to include the fix itself.

Wow... 😁 
I just remembered I recently merged a PR and thought it was that one. But turns out, it was the dependency update 🙈 

@legolas0802 version 1.2.3 is up for your testing 😊

**Comment by legolas0802** [comment] 2019-10-16 18:19
I tried it now and it works, obviously it didn't create the entity for port forwarding

**Comment by mammuth** [comment] 2019-10-16 18:20
Perfect. Thanks for the feedback.

**Closed by mammuth** 2019-10-16 18:20 UTC
Labels: type:bug
