### ISSUE TITLE
0.110 beta deprecated errors

### ISSUE THREAD

**Issue by sagitt** [mammuth/ha-fritzbox-tools#95] opened 2020-05-17 19:58 UTC
Check these errors
0.110 will be released in may 20
thanks

![Schermata 2020-05-17 alle 21 55 05](https://user-images.githubusercontent.com/169086/82158660-7e972e80-9889-11ea-83a4-13bee9cb9e3e.png)
![Schermata 2020-05-17 alle 21 54 28](https://user-images.githubusercontent.com/169086/82158661-8060f200-9889-11ea-842a-7eaa957d4f45.png)

**Comment by mammuth** [comment] 2020-05-17 20:03
Duplicate of #87. Pull requests welcome.

**Closed by mammuth** 2020-05-17 20:03 UTC

**Comment by sagitt** [comment] 2020-05-17 20:17
> Duplicate of #87. Pull requests welcome.

Please explain me, why this is pull request and not an issue? What is the difference?

**Comment by mammuth** [comment] 2020-05-17 20:36
This issue describes the same as the issue #87. That's why I closed this one.

With "pull requests welcome" I wanted to say, that I'm happy if someone contributes the needed changes. Changes can be contributed via "pull requests". Further information: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests
